CREATE DATABASE IF NOT EXISTS `rv_base` CHARACTER SET utf8;

USE `rv_base`;
SET FOREIGN_KEY_CHECKS = 0;

--  Table structure for `USER`
DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOGIN` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `ROLE` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--  Table structure for `RESTAURANT`
DROP TABLE IF EXISTS `RESTAURANT`;
CREATE TABLE `RESTAURANT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--  Table structure for `MENU`
DROP TABLE IF EXISTS `MENU`;
CREATE TABLE `MENU` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RESTAURANT_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),

  FOREIGN KEY (RESTAURANT_ID)
  REFERENCES `RESTAURANT`(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--  Table structure for `MENU`
DROP TABLE IF EXISTS `MENU_ITEM`;
CREATE TABLE `MENU_ITEM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MENU_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),

  FOREIGN KEY (MENU_ID)
  REFERENCES `MENU`(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--  Table structure for `VOTE`
DROP TABLE IF EXISTS `VOTE`;
CREATE TABLE `VOTE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `RESTAURANT_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),

  FOREIGN KEY (USER_ID)
  REFERENCES `USER`(ID),

  FOREIGN KEY (RESTAURANT_ID)
  REFERENCES `RESTAURANT`(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS = 1;
